aws_region      = "us-east-1"
environment     = "dev"
cluster_name    = "jerney-eks"
cluster_version = "1.32"
vpc_cidr        = "10.0.0.0/16"
backend_ecr_repo_name  = "inkwell-backend"
frontend_ecr_repo_name = "inkwell-frontend"
