apiVersion: v1
kind: Service
metadata:
  name: inkwell-backend
  namespace: inkwell
spec:
  selector:
    app: inkwell-backend
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  type: ClusterIP
