apiVersion: v1
kind: Service
metadata:
  name: inkwell-frontend
  namespace: inkwell
spec:
  selector:
    app: inkwell-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer
