apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inkwell-ingress
  namespace: inkwell
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /api/v1/health
spec:
  ingressClassName: alb
  rules:
    - host: app.inkwell25.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: inkwell-backend
                port:
                  number: 5000
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: inkwell-backend
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: inkwell-frontend
                port:
                  number: 80
